export const GET_ALL_ROOMS = "GET_ALL_ROOMS";
export const ROOMS_ERROR = "ROOMS_ERROR";
export const GET_ROOM_DETAILS = "GET_ROOM_DETAILS";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCESS = "REGISTER_USER_SUCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const SET_LOADING = "SET_LOADING";
