export const GET_ALL_ROOMS = "GET_ALL_ROOMS";
export const ROOMS_ERROR = "ROOMS_ERROR";
export const GET_ROOM_DETAILS = "GET_ROOM_DETAILS";

export const REGISTER_USER_SUCESS = "REGISTER_USER_SUCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const SET_LOADING = "SET_LOADING";
export const SET_LOADING_NEW = "SET_LOADING_NEW";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const FORGOT_PASS_SUCCESS = "FORGOT_PASS_SUCCESS";
export const FORGOT_PASS_FAIL = "FORGOT_PASS_FAIL";

export const RESET_PASS_SUCCESS = "RESET_PASS_SUCCESS";
export const RESET_PASS_FAIL = "RESET_PASS_FAIL";

export const CHECK_BOOKING_RESET = "CHECK_BOOKING_RESET";
export const CHECK_BOOKING_SUCCESS = "CHECK_BOOKING_SUCCESS";
export const CHECK_BOOKING_FAIL = "CHECK_BOOKING_FAIL";

export const BOOKED_DATES_SUCCESS = "BOOKED_DATES_SUCCESS";
export const BOOKED_DATES_FAIL = "BOOKED_DATES_FAIL";

export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";
export const GET_BOOKINGS_FAIL = "GET_BOOKINGS_FAIL";

export const GET_BOOKINGS_DETAILS_SUCCESS = "GET_BOOKINGS_DETAILS_SUCCESS";
export const GET_BOOKINGS_DETAILS_FAIL = "GET_BOOKINGS_DETAILS_FAIL";

export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

export const REVIEW_AVAILABILITY_SUCCESS = "REVIEW_AVAILABILITY_SUCCESS";
export const REVIEW_AVAILABILITY_FAIL = "REVIEW_AVAILABILITY_FAIL";
export const GET_ALL_REVIEWS_SUCCESS = "GET_ALL_REVIEWS_SUCCESS";
export const GET_ALL_REVIEWS_FAIL = "GET_ALL_REVIEWS_FAIL";

export const ADMIN_ROOM_SUCCESS = "ADMIN_ROOM_SUCCESS";
export const ADMIN_ROOM_FAIL = "ADMIN_ROOM_FAIL";

export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAIL = "CREATE_ROOM_FAIL";
export const RESET_CREATE_ROOM = "RESET_CREATE_ROOM";

export const UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS";
export const UPDATE_ROOM_RESET = "UPDATE_ROOM_RESET";
export const UPDATE_ROOM_FAIL = "UPDATE_ROOM_FAIL";

export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";
export const DELETE_ROOM_FAIL = "DELETE_ROOM_FAIL";
export const RESET_DELETED_ROOM = "RESET_DELETED_ROOM";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
